apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  labels:
    networking.gke.io/common-webhooks: "true"
  name: copy-mutate-scheduler-profile.config.common-webhooks.networking.gke.io
webhooks:
- admissionReviewVersions:
  - v1beta1
  clientConfig:
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVMRENDQXBTZ0F3SUJBZ0lRSjZLUVJjOFlkRkFBTElnSGl5UFRkVEFOQmdrcWhraUc5dzBCQVFzRkFEQXYKTVMwd0t3WURWUVFERXlRNE1tSmpNMk0wTmkwNU0yTmtMVFExTmpFdE9XTXpaaTAwTVRFMFl6ZzRabVkwWTJZdwpJQmNOTWpJd016QXlNVGN5T1RVMFdoZ1BNakExTWpBeU1qTXhPREk1TlRSYU1DOHhMVEFyQmdOVkJBTVRKRGd5ClltTXpZelEyTFRrelkyUXRORFUyTVMwNVl6Tm1MVFF4TVRSak9EaG1aalJqWmpDQ0FhSXdEUVlKS29aSWh2Y04KQVFFQkJRQURnZ0dQQURDQ0FZb0NnZ0dCQUtXT25ZbU44ZjRPTXp4dXFQeWdSdjZCM04reERKZW9KbVJpd0ZSWAprSVZIU21TTWV4dzV0azZDdk1YUWhiOVRveUVjZ0g0WGFpSHFweXd4aWg3aGJObS9DSlAxUmo2MStjbkN5R2poClZMRVU2ZmlUTDZaT1NPajNuT0dFME5GQnhMTmVvOEh5ODl3aVNlZ2hYaUtORFdvTktCZGFCS2YxaXNzS1JYbVYKSUdXbytmeHFXWEkySXdLeTA2eVJrSE1aaEVQMWNWOGxHMks5OUdFbGJRSUtVbitiUzBGYlkzVWxPbzdKSWJXVgpmTVR5bFViZmpkUFJhZkZXOStodEhHRGQ4Nk5CVmtMdnZLVGZjUU9neFROazRQRG1oUGZrWXBxMmplS1BiNVlyCjFFOW1LVGRESGRhMmtlYlBCcXpndkFFaUZ3VjgwTjlnbnJzWUh5VGZyYTUwaFZzWnVhTC9WQlZIZkVjcHJLZFcKSUZLTzFuYXVBT2F4ZHZ3Q3lZY3N1c21PSUlwOXV0U3JSVmRZdTZIeVlJRnNGSVNSK05hbDA3aVM5MjFBanhHcQp1ZWgzcjE0aTlaTnV0UTgrcDZTNElGTmpRUTFzcmx2dUFyeE1QQmVEc1E2V0RiV1NoR3p5d21zc21pVC96bHBUCjAyZm8yWkNZQTZtUzVXZ2lZb2tyNW9LNXF3SURBUUFCbzBJd1FEQU9CZ05WSFE4QkFmOEVCQU1DQWdRd0R3WUQKVlIwVEFRSC9CQVV3QXdFQi96QWRCZ05WSFE0RUZnUVU5YzZJUnM4OEw4QVRiVGRjUU82WlJxTHRNaGt3RFFZSgpLb1pJaHZjTkFRRUxCUUFEZ2dHQkFKWlNKbWYza1cyQlExVjc2MEFlWW5RUEgwWk9sRElaeEYxOFY1K2daOHBtCkF3TTBmUDFCSUdCdTNWbXJnaUdOM05UMGxJM1hFbFNiQmt5NFI1WWxwdkY5OU1LY05SMW1BUEhlK1E2Y3ZQQXoKRHhKUURoN0dUd0FlbTlHSW83MDQrejMxSzdab0xkdEU0WTdzc21RR1Fhc25JcXlGc2twOGFvUTBWTUtwS0JPdQo2K1djYkluQU5oWWhFd3hKaEszWlNpdmNMMENMMmhxeExJckFWY2E4UkhrSWFGTlE0UFBENXZZMEo4TmNDZjFjCkRtWTR4cHVNcjU4WmhObWhsMmp5NTBSNnVNTDZ2c2lwTWU2eGJmckJGMmxOMDVZL0pyRzBKdllOZzhsT1ZLQ3kKUWpOYy8rcDNjTUxrTzlMM0pQZWV3Y29LWEVyc2tnMFR6TUhHNlNvVGQ2UFpDUTRtR0xpYXAxdTFubkhXWTMxNgppWFowV2cyVUR4VjF0S0ZOdmVZMERZaXpNZ1pmbUJneW1hMFBBSVBVUFppRHp3b2kzRnZLYUhNMUMvMXdBeFhYCmsrN0Jvc2ZnTWRiWGd6UXhKWGZCbDNUWUFOVDA1amFCbnRaVERFOHA4SzI5RnlJU0d2T2xJYjV0cnFlcitGeWwKZkczbm8wekU5NEJRS2tFeXJROVM1UT09Ci0tLS0tRU5EIENFUlRJRklDQVRFLS0tLS0K
    url: https://localhost:5443/webhook/mutate-scheduler-profile
  failurePolicy: Ignore
  matchPolicy: Equivalent
  name: mutate-scheduler-profile.common-webhooks.networking.gke.io
  reinvocationPolicy: Never
  rules:
  - apiGroups:
    - ""
    apiVersions:
    - v1
    operations:
    - CREATE
    resources:
    - pods
    scope: '*'
  sideEffects: None
  timeoutSeconds: 10
